@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":Storage" as storage STORAGE_COLOR

skinparam sequence {
ParticipantBorderColor #000000
ArrowColor #000000
ActorBorderColor #000000
LifeLineBorderColor #000000
LifeLineBackgroundColor #000000
}

user -> ui : "delete task 1"
activate ui UI_COLOR

ui -> logic : execute("delete task 1")
activate logic LOGIC_COLOR

logic -> model : remove(t)
activate model MODEL_COLOR

model --> logic
deactivate model

logic -> storage : saveSchedule(schedule)
activate storage STORAGE_COLOR

storage -> storage : Save to file
activate storage STORAGE_COLOR_T1
storage --> storage
deactivate storage

storage --> logic
deactivate storage

logic --> ui
deactivate logic

ui--> user
deactivate ui
@enduml
