@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class Logic LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class Model MODEL_COLOR
    Class Main #gainsboro
    Class Commons #gainsboro
}

Class "<$user>" as User #white
Class "<$documents>" as File #white


UI -[UI_COLOR_T1]> Logic
UI -right[UI_COLOR_T1]-> Model
Logic -[LOGIC_COLOR_T1]-> Storage
Logic -down[LOGIC_COLOR_T1]-> Model
Main -[#gray]-> UI
Main -[#gray]-> Logic
Main -[#gray]-> Storage
Main -up[#gray]-> Model

Storage .right[STORAGE_COLOR_T1].>File
User ..[#black]> UI
@enduml
