@startuml
!include style.puml

skinparam sequence {
participantBorderColor #000000
ArrowColor #000000
ActorBorderColor #000000
LifeLineBorderColor #000000
LifeLineBackgroundColor #000000
}

skinparam sequenceBoxBorderColor #black

Actor User as user USER_COLOR

box Logic #FFFFFF
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StudyBananasParser" as StudyBananasParser LOGIC_COLOR
participant ":DeleteTaskCommandParser" as DeleteTaskCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model #FFFFFF
participant ":Model" as Model MODEL_COLOR
end box

user -> LogicManager : execute("delete task 1")
activate LogicManager LOGIC_COLOR

LogicManager -> StudyBananasParser : parseCommand("delete task 1")
activate StudyBananasParser LOGIC_COLOR

create DeleteTaskCommandParser
StudyBananasParser -> DeleteTaskCommandParser
activate DeleteTaskCommandParser LOGIC_COLOR

DeleteTaskCommandParser --> StudyBananasParser
deactivate DeleteTaskCommandParser

StudyBananasParser -> DeleteTaskCommandParser : parse("1")
activate DeleteTaskCommandParser LOGIC_COLOR

create DeleteCommand
DeleteTaskCommandParser -> DeleteCommand
activate DeleteCommand LOGIC_COLOR

DeleteCommand --> DeleteTaskCommandParser : d
deactivate DeleteCommand

DeleteTaskCommandParser --> StudyBananasParser : d
deactivate DeleteTaskCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteTaskCommandParser -[hidden]-> StudyBananasParser
destroy DeleteTaskCommandParser

StudyBananasParser --> LogicManager : d
deactivate StudyBananasParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand LOGIC_COLOR

DeleteCommand -> Model : deleteTask(1)
activate Model MODEL_COLOR

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult LOGIC_COLOR

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

user <--LogicManager
deactivate LogicManager
@enduml
