@startuml
!include style.puml

skinparam sequence {
participantBorderColor #000000
ArrowColor #000000
ActorBorderColor #000000
LifeLineBorderColor #000000
LifeLineBackgroundColor #000000
}

skinparam sequenceBoxBorderColor #black

Actor User as user USER_COLOR

box Logic #FFFFFF
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StudyBananasParser" as StudyBananasParser LOGIC_COLOR
participant ":ScheduleParser" as ScheduleParser LOGIC_COLOR
participant ":ScheduleEditCommandParser" as ScheduleEditCommandParser LOGIC_COLOR
participant "e:ScheduleEditCommand" as ScheduleEditCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model #FFFFFF
participant "sm:ScheduleModel" as ScheduleModel MODEL_COLOR
participant "s:Schedule" as Schedule MODEL_COLOR
participant ":UniqueTaskList" as UniqueTaskList MODEL_COLOR
end box

user -> LogicManager : execute("edit task 1 T: Test")
activate LogicManager LOGIC_COLOR

LogicManager -> StudyBananasParser : parseCommand("edit task 1 T: Test")
activate StudyBananasParser LOGIC_COLOR

create ScheduleParser
StudyBananasParser -> ScheduleParser
activate ScheduleParser LOGIC_COLOR

ScheduleParser --> StudyBananasParser : parser
deactivate ScheduleParser

StudyBananasParser -> ScheduleParser : parse("edit task 1 T: Test")
activate ScheduleParser LOGIC_COLOR

create ScheduleEditCommandParser
ScheduleParser -> ScheduleEditCommandParser
activate ScheduleEditCommandParser LOGIC_COLOR

ScheduleEditCommandParser --> ScheduleParser
deactivate

ScheduleParser -> ScheduleEditCommandParser : parse()
activate ScheduleEditCommandParser LOGIC_COLOR

create ScheduleEditCommand
ScheduleEditCommandParser -> ScheduleEditCommand
activate ScheduleEditCommand LOGIC_COLOR

ScheduleEditCommand -->ScheduleEditCommandParser : e
deactivate

ScheduleEditCommandParser --> ScheduleParser : e
deactivate

ScheduleParser --> StudyBananasParser : e
deactivate

StudyBananasParser --> LogicManager : e
deactivate

LogicManager -> ScheduleEditCommand : e.execute()
activate ScheduleEditCommand LOGIC_COLOR

ScheduleEditCommand -> ScheduleModel : sm.setTask()
activate ScheduleModel MODEL_COLOR

ScheduleModel ]-> Schedule : s.setTask()
activate Schedule MODEL_COLOR

Schedule -> UniqueTaskList : setTask()
activate UniqueTaskList MODEL_COLOR

UniqueTaskList --> Schedule
deactivate UniqueTaskList

Schedule --> ScheduleModel
deactivate Schedule

ScheduleModel --> ScheduleEditCommand
deactivate ScheduleModel

create CommandResult
ScheduleEditCommand -> CommandResult
activate CommandResult LOGIC_COLOR

CommandResult --> ScheduleEditCommand
deactivate

ScheduleEditCommand --> LogicManager : result
deactivate

user <--LogicManager
deactivate LogicManager

'Hidden arrow to position the destroy marker below the end of the activation bar.

@enduml
