@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor #black
skinparam classBackgroundColor LOGIC_COLOR
skinparam classBorderColor LOGIC_COLOR_T1
skinparam noteBorderColor LOGIC_COLOR_T1

package Logic {

package Parser {
Class StudyBananasParser
Class XYZCommandParser
}

package Command {
Class XYZCommand
Class CommandResult
Class "{abstract}\nCommand" as Command
}

Interface Logic <<Interface>>
Class LogicManager
}

package Model{
Class HiddenModel #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .up.|> Logic
LogicManager -->"1" StudyBananasParser
StudyBananasParser ..> XYZCommandParser : creates >
XYZCommandParser ..> XYZCommand : creates >
XYZCommand -up-|> Command
LogicManager .left.> Command : executes >

LogicManager --> Model
Command .up.> Model
note right of XYZCommand LOGIC_COLOR: XYZCommand = AddTaskCommand, \nQuizCommand, etc

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult
CommandResult -[hidden]-> Parser
@enduml
