@startuml
!include style.puml

skinparam arrowThickness 1.1
skinparam arrowColor #black
skinparam classBackgroundColor MODEL_COLOR
skinparam classBorderColor MODEL_COLOR_T1

Package "timeformat"<<Rectangle>>{
    Interface TimeFormat MODEL_COLOR
    Class IsoDate
    Class IsoDateTime
    Class WordDateTime
    Class NewDateTime
    Class TimeFormatChecker
}


IsoDate .up.|> TimeFormat
IsoDateTime .up.|> TimeFormat
WordDateTime .up.|> TimeFormat
NewDateTime .up.|> TimeFormat

TimeFormatChecker .up.> IsoDate
TimeFormatChecker .up.> IsoDateTime
TimeFormatChecker .up.> WordDateTime
TimeFormatChecker .[MODEL_COLOR_T2]up.> NewDateTime


@enduml
