@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR_T1
skinparam classBackgroundColor MODEL_COLOR
skinparam classBorderColor MODEL_COLOR_T1

title Quiz

package FlashcardSet {
    class State1 as "__flashcard1:Flashcard__"
    class State2 as "__flashcard2:Flashcard__"
    class State3 as "__flashcard3:Flashcard__"
}
State1 -[hidden]right-> State2
State2 -[hidden]right-> State3
class Pointer as "Current Index" #FFFFF
Pointer -up-> State3
hide State3
@end
