@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor USER_COLOR
skinparam classBackgroundColor USER_COLOR
skinparam classBorderColor USER_COLOR
skinparam activity {
BorderColor #gold
DiamondBorderColor #gold
}

start
:User executes start quiz command;

repeat :System shows question;
  :User answers question;
  :System stores answer to question;
  :System shows the correct answer;
  if () then ([correct user answer])
      :User marks answer as right;
      :System increments points scored;
  else ([else])
      :User marks answer as wrong;
  endif
  :System stores correctness response to question;
repeat while () is ([quiz end not reached]);
:System shows quiz score and statistics;
stop
@enduml
