@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor #black
skinparam classBackgroundColor MODEL_COLOR
skinparam classBorderColor MODEL_COLOR_T1

Class QuizRecords

Package Quiz {
Class Quiz
Class FlashcardSet
Class FlashcardSetName
Class UniqueQuizMap
}

QuizRecords *-down-> "1" UniqueQuizMap
QuizRecords -[hidden]-> FlashcardSetName
Quiz *-> "1" FlashcardSetName
UniqueQuizMap o-down-> "*" FlashcardSetName
UniqueQuizMap o-down-> "*" Quiz
Quiz *-down-> "1" FlashcardSet

@enduml
