@startuml

!include style.puml

class SingleUiState UI_COLOR
class SidebarTab UI_COLOR

skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam arrowThickness 1.1
skinparam arrowColor #black
skinparam classBackgroundColor UI_COLOR
skinparam classBorderColor UI_COLOR_T1


SingleUiState <-[UI_COLOR_T1]- SidebarTab : update




@enduml
