@startuml

!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam arrowThickness 1.1
skinparam arrowColor #black
skinparam classBackgroundColor UI_COLOR
skinparam classBorderColor UI_COLOR_T1

Interface Observer <<Interface>>
Interface Observable <<Interface>>

class SingleUiState
class MainWindow

Observable <|-- SingleUiState
Observer <|-- MainWindow

MainWindow ..> SingleUiState : subscribe

interface Observer {
subscribe(Observable o)
update(UiStateType state)
}

interface Observable {
register(Observer o)
inform()
}

class SingleUiState {
Schedule (the default state)
}



@enduml
