@startuml

!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam arrowThickness 1.1
skinparam arrowColor #black
skinparam classBackgroundColor UI_COLOR
skinparam classBorderColor UI_COLOR_T1

class SingleUiState
class MainWindow
class SidebarTab

SingleUiState <.. MainWindow : subscribe
SingleUiState <.. SidebarTab : subscribe

class SingleUiState {
Schedule (the default state)
}



@enduml
