@startuml

!include style.puml


class SingleUiState UI_COLOR
class MainWindow UI_COLOR
class SidebarTab UI_COLOR

SingleUiState -[UI_COLOR_T1]-> MainWindow : inform
SingleUiState -[UI_COLOR_T1]-> SidebarTab : inform



@enduml
