@startuml

!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

class SingleUiState
class MainWindow
class SidebarTab

SingleUiState --> MainWindow : inform
SingleUiState --> SidebarTab : inform

class SingleUiState {
NewState
}



@enduml
