@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Quiz

package FlashcardSet {
    class State1 as "__flashcard1:Flashcard__"
    class State2 as "__flashcard2:Flashcard__"
}
State1 -[hidden]right-> State2
class Pointer as "Current Index" #FFFFF
Pointer -up-> State1
@end
