@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR_T1
skinparam classBackgroundColor MODEL_COLOR

Class StartCommand LOGIC_COLOR
Class QuizModelManager
Class Quiz

QuizModelManager -> "0..1" Quiz
StartCommand --> Quiz LOGIC_COLOR
StartCommand .> QuizModelManager LOGIC_COLOR
@enduml
