@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor #black
skinparam classBackgroundColor MODEL_COLOR

class AnswerCommand LOGIC_COLOR
class QuizModelManager
class Quiz

AnswerCommand .> QuizModelManager
QuizModelManager -> "0..1" Quiz
@enduml
