@startuml
skinparam classAttributeIconSize 0

class AnswerCommand {
 - userAnswer:String
 + execute()
}

class QuizModelManager {
+saveAnswer()
+getAnswer()
}

class Quiz {
-userAnswers:String[]
+saveAnswer()
+getAnswer()
}

AnswerCommand .> QuizModelManager
QuizModelManager -> "0..1" Quiz
@enduml
