@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor #black
skinparam classBackgroundColor LOGIC_COLOR
skinparam classBorderColor LOGIC_COLOR_T1

package Parser {
Class StudyBananasParser
Interface Parser <<Interface>>
Class FlashcardParser
Class ScheduleParser
Class QuizParser
Class GeneralParser
}

StudyBananasParser ..> FlashcardParser : creates >
StudyBananasParser ..> ScheduleParser : creates >
StudyBananasParser ..> QuizParser : creates >
StudyBananasParser ..> GeneralParser : creates >
FlashcardParser ..|> Parser
ScheduleParser ..|> Parser
QuizParser ..|> Parser
GeneralParser ..|> Parser

@enduml
