/'
 'Commonly used styles and colors across diagrams.
 'Refer to https://plantuml-documentation.readthedocs.io/en/latest for a more
 'comprehensive list of skinparams.
 '/


'T1 is darker shade.

!define UI_COLOR #F8CECC
!define UI_COLOR_T1 #DAA5A3

!define LOGIC_COLOR #DAE8FC
!define LOGIC_COLOR_T1 #B2C4DD

!define MODEL_COLOR #D5E8D4
!define MODEL_COLOR_T1 #BED7AF

!define STORAGE_COLOR #FFE6CC
!define STORAGE_COLOR_T1 #EACB7A

!define USER_COLOR #000000

skinparam BackgroundColor #FFFFFFF

skinparam Shadowing false

skinparam Class {
    FontColor #000000
    BorderThickness 1
    BorderColor #FFFFFF
    StereotypeFontColor #000000
    FontName Arial
}

skinparam Object {
    FontColor #000000
    BorderThickness 1
    BorderColor #FFFFFF
    StereotypeFontColor #000000
    FontName Arial
}

skinparam Actor {
    BorderColor USER_COLOR
    Color USER_COLOR
    FontName Arial
}

skinparam Sequence {
    MessageAlign center
    BoxFontSize 15
    BoxPadding 0
    BoxFontColor #000000
    FontName Arial
}

skinparam Participant {
    FontColor #000000
    Padding 20
}

skinparam MinClassWidth 50
skinparam ParticipantPadding 10
skinparam Shadowing false
skinparam DefaultTextAlignment center
skinparam packageStyle Rectangle

hide footbox
hide members
hide circle
