@startuml

!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor #black
skinparam classBackgroundColor MODEL_COLOR
skinparam classBorderColor MODEL_COLOR_T1

Class Task
Class Title
Class Description
Class DateTime
Class Duration

Task *--> "1" Title
Task *--> "0..1" Description
Task *--> "0..1" DateTime
Task *--> "0..1" Duration

@enduml
