@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T1
skinparam classBackgroundColor UI_COLOR
skinparam classBorderColor UI_COLOR_T1

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class ScheduleUi
Class FlashcardUi
Class QuizUi
Class Sidebar

}


Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow *-down-> ScheduleUi
MainWindow *-down-> FlashcardUi
MainWindow *-down-> QuizUi
MainWindow *-down-> Sidebar


MainWindow -left-|> UiPart

ScheduleUi --|> UiPart
FlashcardUi --|> UiPart
QuizUi --|> UiPart
Sidebar --|> UiPart




MainWindow -[hidden]-|> UiPart
@enduml
