@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor #black
skinparam classBackgroundColor UI_COLOR
skinparam classBorderColor UI_COLOR_T1

package UI <<Rectangle>>{
Class UiManager
Class MainWindow
Class ScheduleUi
Class FlashcardUi
Class QuizUi
Class UpcomingSchedule
Class TaskDetailPanel
Class TaskDetailSkin
Class FlashcardSetListPanel
package Commons <<Rectangle>>{
Class GlobalState
}

}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

skinparam component {
  FontSize 10
  ArrowFontName Arial
  ArrowFontColor black
}

UiManager -left-> Logic
UiManager -right-> MainWindow
UiManager -right-> GlobalState : initiate

MainWindow *-down-> QuizUi
MainWindow *-down-> FlashcardUi
MainWindow *-down-> ScheduleUi : Logic



QuizUi *-down-> FlashcardSetListPanel


FlashcardUi *-down-> FlashcardSetListPanel


ScheduleUi *-down-> UpcomingSchedule
ScheduleUi *-down-> TaskDetailPanel : Logic




TaskDetailPanel *-down-> TaskDetailSkin : Logic





@enduml
