@startuml
!include style.puml
skinparam ArrowFontColor red

Package "Ui"<<Rectangle>>{
    Class UiComponent #1a8cff
    Class CallBack #ffa64d
    Class Listener #70db70
    Class DynamicState MODEL_COLOR
}

skinparam component {
  FontSize 10
  ArrowFontName Arial
  ArrowColor black
  ArrowFontColor red
}



Listener -left-> CallBack : trigger
CallBack -up-> UiComponent : update

Listener <-- DynamicState : notify

Class HiddenOutside #FFFFFF
DynamicState <.. HiddenOutside: action



@enduml